# Generated by Django 6.0.3 on 2026-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='solution_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
