# Generated by Django 6.0.3 on 2026-04-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_expected_output_lesson_solution_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML')], default='python', max_length=20),
        ),
    ]
